feat: add checkpoint_delay, checkpoint_percent to instance refresh
terraform-aws-modules/terraform-aws-autoscaling pull request #166
Opened 2021-11-12 16:08 UTC by aarmstrong-gel

## Description
checkpoint_delay - (Optional) The number of seconds to wait after a checkpoint. Defaults to 3600.
checkpoint_percentages - (Optional) List of percentages for each checkpoint. Values must be unique and in ascending order. To replace all instances, the final number must be 100.

Parameter docs:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#preferences

## How Has This Been Tested?
- I have tested and validated these changes using one or more of the provided `examples/*` projects, triggered instance refresh by editing a tag and redeploying

2021-11-12 16:32 UTC, bryantbiggs requested changes
this looks great, but we'll need to bump the min version to v3.64.0 to support this https://github.com/hashicorp/terraform-provider-aws/pull/21115

2021-11-15 10:33 UTC, aarmstrong-gel commented
any further input from me on this?

2021-11-15 11:07 UTC, antonbabenko commented
@bryantbiggs Do you have any idea why pre-commit checks succeeded for this commit - db520a9 ( https://github.com/terraform-aws-modules/terraform-aws-autoscaling/runs/4210380482?check_suite_focus=true ) though the AWS provider version was not updated in README? When I run `pre-commit run -a` locally it correctly updated the files.

@aarmstrong-gel Looks good, I will merge it now. Thank you!

2021-11-15 11:14 UTC, merged

2021-11-15 11:16 UTC, antonbabenko commented
Here we go!

[v4.8.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v4.8.0) has been just released.

2021-11-15 12:42 UTC, bryantbiggs commented
@antonbabenko it looks like a bug in the existing/old CI check workflow. I ran some tests to confirm
- see individual commits on this https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/167
- confirmed it works as intended on new workflow https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/258